# Site settings
name: Jeff的博客
email: tae44@vip.qq.com
author: Jeff
url: http://www.baidu.com
resume_site: https://tae44.github.io/
github: https://github.com/tae44
baseurl: ""
description: Hard work leads to success.
meta_description: 姜思洋;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: tae44
highlighter: rouge

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

